### ISSUE TITLE
How to bind to non localhost

### ISSUE THREAD

**Issue by gingray** [ohler55/agoo#35]
How to bind to non localhost using example
```bash
ruby hello.rb
```

**Comment by gingray** [comment]
I've find option `bind` but it will be better if it will be documented
```ruby
Agoo::Server.init(6464, 'root', {bind: 'tcp://0.0.0.0'})
```

**Comment by ohler55** [comment]
Hmm, It should have been documented in the `Server.init()` method but I just looked at the ruby gem docs and they seem to be broken. I'll track that down and see why the docs are not being generated correctly.

**Comment by ohler55** [comment]
I see what happened. Garbage directory was picked up when I did the release. It will be gone on the next release.

**Comment by gingray** [comment]
@ohler55 thank you for fast response I've spend some time to figure how to get this. I'm sure that help people in future. Me with my friends make some performance test for web servers and using this one I get 25_478rps (max was 29_000rps) (test was on amazon instance t3.small using wrk with following params ```wrk -c400 -t20 -d100s ```)

Also I've face that If I add more workers because on instance was 2vcpu I've set 2 workers performance was significant lower (~15_000rps) than when I use single worker version maybe there a room for improvements.
ruby version was used ```ruby-2.3.5```

app example [https://github.com/gingray/orelrb_contest_2](url)

**Comment by ohler55** [comment]
I broke the performance on the last release and will be making a new one that puts it back where it was tonight. You should see closer to 100_000 rps even on a 2 core machine. Faster than that for static asset fetches. Why are you using such as old ruby version?

Be careful when having `wrk` use that many threads if it is running on the same virtual machine. It will take up more CPU than the server. Maybe you've figured that out since you were asking about binds.

Anyway, wait a day and try the benchmarks again. I might have a new release out in a few hours if all goes smoothly.

**Comment by ohler55** [comment]
Released 2.5.5. Please give it another try.

**Comment by gingray** [comment]
@ohler55 thank you I'll do. Do you want me to share results ? In terms of test we use two instance on amazon on same region one for wrk and another one for app.

**Comment by gingray** [comment]
@ohler55 I've test on new server version. I've increase performance by 2K RPS it was various from (~27_000k - 30_000k). I've test on ruby version 
`ruby-2.5.3`
 `Ubuntu 16.04` 
`Amazon t3.small`
I've also faced with issue I don't know why it so but if I set amount of workers to 2 performance is lower significantly like 15_000 - 17_000k RPS

**Comment by ohler55** [comment]
With only 2 cores there are not many threads to go around. Since the `hello.rb` is very light weight the IO is probably more expensive. By having more than one worker you are increasing the thread context switching which costs more than running the `hello.rb` Ruby code. Best to leave it as a single process.

Another factor may be the network. What network speed has been allocated? A quick way to see if that is an issue is run `wrk`, or my `perfer` on the same virtual machine as Agoo. I'd cut the threads back to 2 though. For those speeds, 2 threads should be more than enough.

If you are looking for the best throughput, play around with the connections and threads. Something you can try with `perfer` is change the backlog the tool will allow. Even more important, keep the connection open. That is how modern browsers work. Once a connection is established it is reused.

When I use `perfer` the command line options I use are:

`perfer -p "/hello" -k -b 2 -t 2 -c 200 -d 10 localhost:6464`

Vary each option as you see fit of course. `perfer` is at https://github.com/ohler55/perfer.

**Comment by ohler55** [comment]
Oh, one more thing. Turn off the verbose logging if you haven't already by setting the log states to false.

**Comment by ohler55** [comment]
Any updates on this? Can it be closed?

**Comment by gingray** [comment]
@ohler55 sure sorry for the late response and thank you for your recommendations
